### ISSUE TITLE
help for samsung galaxy j7

### ISSUE THREAD

**Issue by zbot108** [sriharshaarangi/BatteryChargeLimit#110] opened 2018-05-01 19:19 UTC
hi! 

i rooted my samsung galaxy j7 but when i run the app, i get an error message "app is denied ROOT access or device is not rooted!" and then it just closes. 

is my device supported? 

thanks!

**Comment by milux** [comment] 2018-05-02 16:34
Which rooting method? Which SU control app? Have you allowed root access for BCL?
Please provide more information!

**Comment by milux** [comment] 2018-05-03 13:06
Alright, that's what I suspected. ^^
Let me ask you some questions:
- Do you understand what rooting is and how it works?
- Are you aware of the consequences and implications of rooting?
- Du you know that most banking apps, payment apps, and some games like PoGo may stop working on rooted phones, and there is no guarantee that root hiding will continue to work as it does right now?
- Are you willing to offer the warranty on your device, if any? (OEMs tend to refuse warranty if they receive defective phones that are rooted, regardless of whether or not the problem is related to rooting.)
If you cannot safely answer all those questions with yes, you should think twice whether you really want to do that.

**Comment by sriharshaarangi** [comment] 2018-05-15 01:16
Closing this, since it is not an issue with the app.

**Closed by sriharshaarangi** 2018-05-15 01:16 UTC
