### ISSUE TITLE
Info (V and T) are different in main app window and notification.

### ISSUE THREAD

**Issue by vovodroid** [sriharshaarangi/BatteryChargeLimit#17] opened 2017-07-15 17:49 UTC

**Comment by milux** [comment] 2017-07-28 17:17
I could not reproduce this issue, although it might theoretically be possible, because those updates are performed through 2 different BroadcastListeners.
Could it be that you observe this behavior exactly when your device is in **DISCHARGING** mode?

**Comment by milux** [comment] 2017-08-15 09:14
OK, since there was no feedback for quite a while, I hope that this issue is not relevant anymore and close this. Please comment if it happens again.

**Closed by milux** 2017-08-15 09:14 UTC
Labels: bug

**Comment by vovodroid** [comment] 2017-08-16 13:55
> Could it be that you observe this behavior exactly when your device is in DISCHARGING mode?
Yes, it happens after charge stop, but it seems to be synchronized after some time, so I caught it by chance.
