### ISSUE TITLE
Nexus 5 support

### ISSUE THREAD

**Issue by fredsilon** [sriharshaarangi/BatteryChargeLimit#45] opened 2017-09-03 18:29 UTC
_Nexus 5 running LineageOS 14.1-20170829-NIGHTLY-hammerhead_

Control File (default = read-only ... -r--r--r--):
**/sys/class/power_supply/ac/charging_enabled**
1 = charging enabled
0 = charging disabled

I had to change the file to read/write:
`/sys/class/power_supply/ac # chmod u+w charging_enabled `

**Testing**
```
/sys/class/power_supply/ac # echo 0 > charging_enabled
/sys/class/power_supply/ac # cat status
Not charging
```
Waited for 10 minutes ... battery charge level didn't go up.

After setting the file back to 1, the phone got charged again and battery charge level increased.
```
/sys/class/power_supply/ac # echo 1 > charging_enabled
/sys/class/power_supply/ac # cat status
Charging
```

**Comment by milux** [comment] 2017-09-04 11:24
Will be included in next release.

**Comment by fredsilon** [comment] 2017-09-05 16:34
thanks, that was quick :), working great with release 1.0.4

There is only one issue left for my device (maybe it's different with others):

After each reboot, I have to make the control file writable via adb:

`/sys/class/power_supply/ac # chmod u+w charging_enabled`

**Comment by milux** [comment] 2017-09-06 13:51
Otherwise BCL fails to overwrite?
If that is the case, could you please open a new issue for it, because it will require implementing a new option for this.
Thanks for reporting back, will remove the experimental status flag.

**Closed by milux** 2017-09-06 13:51 UTC
Labels: enhancement

**Comment by qtwyeuritoiy** [comment] 2017-10-02 16:34
It is an issue for me and I can confirm that it works with the write permission. Currently I've automated the process with Termux but I hope it would be resolven in the future release.
